### ISSUE TITLE
Waiting for user to authenticate...

### ISSUE THREAD

**Issue by timdonovanuk** [adobe/aem-assets-selectors-mfe-examples#7]
The auth modal pops up, and authentication takes place, but no callback happens to the other window:

![image](https://github.com/adobe/aem-assets-selectors-mfe-examples/assets/8156439/b241873a-e7b4-4880-96ee-bfa5b71afd6d)

![image](https://github.com/adobe/aem-assets-selectors-mfe-examples/assets/8156439/5da09cd5-5fa2-4d75-984a-36091e0d2d39)

This is the same for every demo.

**Comment by nazimamin** [comment]
This is expected. Your redirectUrl (in this case window.location.href) must match the `redirectUrl` that was specifically setup for your AEM Assets `ImsClientId` . Arbitrary `redirectUrl` (the way you have it) will not work.

**Comment by timdonovanuk** [comment]
Thank you - could you please elaborate on steps to configure this? Or point to some documentation? If examples not working "is expected" perhaps the installation documentation could mention this and detail how to install.

**Comment by vedgunjan** [comment]
@timdonovanuk 
Where you able to find out the solution to you problem? I'm also running into same issue.

@nazimamin Can you plz share any documentation that we can refer? 

Thanks!

**Comment by timdonovanuk** [comment]
I didn't get it working. @nazimamin comment assumes you know how to[ "draw the rest of the owl"](https://knowyourmeme.com/memes/how-to-draw-an-owl).

**Comment by nazimamin** [comment]
@timdonovanuk apologies for the confusion and that you weren't able to solve your issue. Thanks for opening this issue. I've added a warning in #9 so that it is clear what to expect. In order to have you on-boarded so for Asset Selector to work end-to-end in your public integration, you will need to have a client id provisioned. Can you kindly open a support ticket from your AEM Admin Console and provide the below two items: 

- Program ID and Environment ID for the AEM CS instance
- Domain names where the integrating application is hosted

Someone from support will reach back out to you when that is complete and provide all the necessary configuration that you need. 

For now, I'll close this ticket. Feel free to re-open/create another if your concerns aren't resolved after following the above.
